### ISSUE TITLE
Please add copy of GPL license

### ISSUE THREAD

**Issue by tyll** [jeroennijhof/vncpwd#1]
According to the license information for the project there should be a GPL license file but there is none. Please consider to add one. For reference, see also:

https://www.gnu.org/licenses/gpl-howto.en.html

Thank you.

**Comment by tyll** [comment]
I noticed this when reviewing a submission to include this nice tool in the Fedora Linux distribution btw. https://bugzilla.redhat.com/show_bug.cgi?id=1433657

**Comment by jeroennijhof** [comment]
I have add a copy of the GPLv3 license in the repo, thank you for pointing this out.

**Comment by xambroz** [comment]
Adding the license is probabli adding some additional questions.
The code seems to be licensed with GPLv2+, but the license file is GPLv3.
Did you meant to change the licensing also in the vncpwd.c ?

Thank you.
