### ISSUE TITLE
License file not aligned with the vncpwd.c

### ISSUE THREAD

**Issue by xambroz** [jeroennijhof/vncpwd#2]
The license in vncpwd.c is GPLv2+ while the LICENSE file is GPLv3.
Did you meant to change the licensing of the vncpwd.c also to GPLv3 ?

Thank you
Michal Ambroz

**Comment by xambroz** [comment]
Please note the GPLv2+ license is also mentioned in the README file

**Comment by jeroennijhof** [comment]
Fixed
