### ISSUE TITLE
Wrong FSF address in the source code

### ISSUE THREAD

**Issue by xambroz** [jeroennijhof/vncpwd#3]
Hello,
Robert-André Mauchin noticed during the vncpwd package review for Fedora that the address of the  Free Software Foundation in the source code and a README file is obsolete and potentially target to misuse. 

The address should be:
Free Software Foundation, Inc.,  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 

Currently there is:
Free Software   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

Best regards
Michal Ambroz

**Comment by jeroennijhof** [comment]
Fixed
