### ISSUE TITLE
Password still not decrypted after running

### ISSUE THREAD

**Issue by dm20** [jeroennijhof/vncpwd#7]
Hi there, super cool program. 

**Would you mind giving some explanation or background as to how it works?** 

The main reason for this issue is that after I ran the program, it returned an encrypted password. 

My vnc password is stored in /Library/vnc/vncpasswd so I ran the following command after making the files
`./vncpwd /Library/vnc/vncpasswd`

And it returned

`Password: ?(NӬ??`

Any thoughts as to why this is the output?

**Comment by alex-eri** [comment]
what type of vnc server are used?

**Comment by dos145** [comment]
Hello !

Thanks for the code but I try to decode an UltraVNC password (hexa) and I have the same issue.
I create a new file that only contain the password but the result il bad...

Anys idea ?

**Comment by jeroennijhof** [comment]
It currently only supports chars (bytes) and not hex stored passwords. You can however convert the hex to bytes and then decrypt the password with this tool.
